import turtle
turtle.dot()
turtle.penup()
turtle.forward(75)
turtle.pendown()
turtle.setheading(270)
turtle.forward(75)
turtle.dot()
turtle.setheading(180)

turtle.forward(15)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(37.5)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(37.5)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(15)

turtle.dot()
turtle.setheading(90)
turtle.forward(150)
turtle.dot()
turtle.setheading(0)

turtle.forward(15)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(37.5)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(37.5)
turtle.penup()
turtle.forward(15)
turtle.pendown()
turtle.forward(15)

turtle.dot()
turtle.setheading(270)
turtle.forward(150)
turtle.setheading(135)
turtle.forward(212)
turtle.setheading(270)
turtle.forward(150)
turtle.setheading(45)
turtle.forward(212)

turtle.hideturtle()