import turtle
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.setheading(45)
turtle.forward(100)
turtle.setheading(315)
turtle.forward(100)
turtle.setheading(225)
turtle.forward(100)
turtle.setheading(135)
turtle.forward(100)
turtle.end_fill()

turtle.fillcolor('red')
turtle.begin_fill()
turtle.forward(100)
turtle.setheading(225)
turtle.forward(100)
turtle.setheading(315)
turtle.forward(100)
turtle.setheading(45)
turtle.forward(100)
turtle.end_fill()

turtle.hideturtle()