import turtle

turtle.forward(100)
turtle.write('East')
turtle.setheading(180)
turtle.forward(200)
turtle.write('West')
turtle.setheading(0)
turtle.forward(100)
turtle.setheading(270)
turtle.forward(100)
turtle.write('South')
turtle.setheading(90)
turtle.forward(200)
turtle.write('North')
turtle.setheading(270)
turtle.forward(100)
turtle.setheading(180)
turtle.forward(25)
turtle.circle(10)